version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=sysadmin
      - POSTGRES_DB=sw      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@sw.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "54321:80"
    depends_on:
      - postgres